@echo off
echo Initializing Booking System...

echo Setting up virtual environment...
python -m venv venv
call venv\Scripts\activate

echo Installing dependencies...
pip install -r requirements.txt

echo Starting applications...
python run_apps.py